# Generated by Django 2.2.5 on 2022-06-14 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220614_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favs',
            field=models.ManyToManyField(null=True, related_name='favs', to='rooms.Room'),
        ),
    ]
