# Generated by Django 2.2.5 on 2022-06-14 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220614_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favs',
            field=models.ManyToManyField(related_name='favs', to='rooms.Room'),
        ),
    ]
